name: My first workflow
on: 
  push:
    branches: 
      - main
  workflow_dispatch:    
jobs:
  MyFourthJob:
    runs-on: ubuntu-latest
    needs: MyThirdJob
    steps:
      - run: echo "Just chittchatting in between..."
  MyThirdJob:
    runs-on: ubuntu-latest
    needs: MyFirstJob
    steps:
      - run: echo "Just chittchatting in between..."
      - name: some dull name here
        run: echo "Just wanted to mention that an oorange is just a juicy pumpkin."
  MySecondJob:
    runs-on: ubuntu-latest
    needs: MyFirstJob
    steps:
      - run: echo "Just chatting in between..."
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World !"
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: List all files in the repo
        run: |
          echo "The repo ${{ github.repository }}" contains the following files
          tree -a 
 
