name: My first workflow
on: 
  push:
    branches: 
      - main
  workflow_dispatch: 
    inputs:
      comment:
        description: Add a comment
        required: false
        default: "no comment provided"
# jobs run in parallel if not specified to wait for one another using "needs"  
jobs:
  MyFourthJob:
    # only runs when the underlying branch is "bobobranch"
    if: ${{ github.ref == 'refs/heads/bobobranch' }}
    strategy: 
      fail-fast: false
      max-parallel: 2
      matrix:
        first_name: ["hans", "karl"]
        last_name: ["meier", "mueller", "schulze"]
    #     
    runs-on: ubuntu-latest
    needs: MyThirdJob
    steps:
      - run: echo "${{matrix.first_name}} ${{matrix.last_name}}"
  MyThirdJob:
    runs-on: ubuntu-latest
    needs: MyFirstJob
    # steps always run in sequence
    steps:
      - run: echo "Just chittchatting in between..."
      - name: some dull name here
        run: echo "Just wanted to mention that an oorange is just a juicy pumpkin."
      - name: summup  
        run: echo "<h1>Great feature!</h1>" >> $GITHUB_STEP_SUMMARY
      - name: Set color
        id: color-generator
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        run: echo "${{ steps.color-generator.outputs.SELECTED_COLOR }}"
  MySecondJob:
    runs-on: ubuntu-latest
    needs: MyFirstJob
    steps:
      - run: echo "Just chatting in between..."
      - name: Write Summary from Action
        uses: actions/github-script@v6.1.0
        with:
          script: |
            await core.summary
            .addHeading('Test Results')
            .addTable([
              [{data: 'File', header: true}, {data: 'Result', header: true}],
              ['foo.js', 'Pass ✅'],
              ['bar.js', 'Fail ❌'],
              ['test.js', 'Pass ✅']
            ])
            .addLink('View staging deployment!', 'https://github.com')
            .write()
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World !"
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: List all files in the repo
        run: |
          echo "The repo ${{ github.repository }}" contains the following files
          tree -a 
 
